In [2]:
import pandas as pd
import numpy as np

In [26]:
len_desired = 5500
rand_1 = [np.random.randint(2) for i in range(len_desired)]
rand_2 = [np.random.randint(2) for i in range(len_desired)]
rand_3 = [np.random.randint(2) for i in range(len_desired)]

In [38]:
def gen_list(in_com):
    if(in_com==0):
        return rand_1
    if(in_com==1):
        return rand_2
    if(in_com==2):
        return rand_3
    if(in_com==3):
        return [abs(rand_1[i]-1) for i in range(len_desired)]
    if(in_com==4):
        return [abs(rand_2[i]-1) for i in range(len_desired)]
    if(in_com==5):
        return [abs(rand_3[i]-1) for i in range(len_desired)]

In [39]:
data_perf = pd.DataFrame()

data_perf["channel0"] = rand_1
data_perf["channel1"] = rand_2
data_perf["channel2"] = rand_3


for i in range(13):
    choice = np.random.randint(6)
    data_perf["channel"+str(i+4)] = gen_list(choice)

In [40]:
data_perf.head()

,channel1,channel2,channel3,channel4,channel5,channel6,channel7,channel8,channel9,channel10,channel11,channel12,channel13,channel14,channel15,channel16
0,1,0,0,0,1,0,1,1,1,1,0,0,1,0,0,1
1,1,0,1,1,1,0,1,1,0,1,0,0,0,0,1,1
2,0,1,1,1,0,1,0,0,0,0,1,1,0,1,1,0
3,0,0,1,1,0,0,1,1,0,0,1,1,0,1,1,0
4,0,0,0,0,0,0,1,1,1,0,1,1,1,1,0,0

In [41]:
data_perf.to_csv("./dataset/perfectly_correlated.csv",index=False)